
name: Send nostr Event on Push

on:
  push

jobs:
  units:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Publish to nostr
        uses: theborakompanioni/nostr-action@v1
        with:
          key: ${{ secrets.NOSTR_KEY }}
          relay: wss://nostr.chaker.net
          content: |
            ${{ github.actor }} pushed to branch ${{ github.ref_name }}
            https://github.com/${{ github.repository }}/compare/${{ github.event.before }}...${{ github.event.after }}
